spring:
  application:
    name: blog-backend
  cache:
    jcache:
      config: classpath:ehcache.xml
  datasource:
    url: jdbc:h2:file:./data/blog
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
  flyway:
    locations:
    - classpath:db/migration/{vendor}
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 9090
logging:
  level:
    root: INFO
    com.example.blog: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.security: DEBUG
